// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	/**  Informa a versão, o commit e a plataforma do app. */
	appInfo: () => typedError<AppInfo, AppError>(__TAURI_INVOKE("app_info")),
	/**  Configurações atuais. */
	settingsGet: () => typedError<Settings, AppError>(__TAURI_INVOKE("settings_get")),
	/**  Altera as configurações e devolve como ficaram. O nível dos registros vale na hora. */
	settingsUpdate: (patch: SettingsPatch) => typedError<Settings, AppError>(__TAURI_INVOKE("settings_update", { patch })),
	/**  Operações em andamento e as últimas concluídas (painel Tarefas). */
	operationsList: () => typedError<OperationSnapshot[], AppError>(__TAURI_INVOKE("operations_list")),
	/**  Pede o cancelamento de uma operação. */
	operationCancel: (operationId: OperationId) => typedError<null, AppError>(__TAURI_INVOKE("operation_cancel", { operationId })),
	/**  Onde as chaves ficam e quais estão configuradas. */
	secretsStatus: () => typedError<SecretsStatus, AppError>(__TAURI_INVOKE("secrets_status")),
	/**  Grava uma chave digitada e devolve o estado. */
	secretsSet: (kind: SecretKind, value: string) => typedError<SecretsStatus, AppError>(__TAURI_INVOKE("secrets_set", { kind, value })),
	/**  Testa uma chave na API dela. */
	secretsTest: (kind: SecretKind) => typedError<SecretTestResult, AppError>(__TAURI_INVOKE("secrets_test", { kind })),
	/**  Apaga uma chave e devolve o estado. */
	secretsRemove: (kind: SecretKind) => typedError<SecretsStatus, AppError>(__TAURI_INVOKE("secrets_remove", { kind })),
	/**  Modo das chaves em uso. */
	secretsBackendGet: () => typedError<BackendKind, AppError>(__TAURI_INVOKE("secrets_backend_get")),
	/**  Troca o modo das chaves (cofre ↔ `.env`), movendo-as, e devolve o estado. */
	secretsBackendSet: (backend: BackendKind) => typedError<SecretsStatus, AppError>(__TAURI_INVOKE("secrets_backend_set", { backend })),
};

/** Events */
export const events = {
	operationUpdated: makeEvent<OperationUpdated>("operation-updated"),
	packChanged: makeEvent<PackChanged>("pack-changed"),
};

/* Types */
/**
 *  Códigos do domínio `ai`. O código é contrato: renomear é mudança de contrato;
 *  acrescentar é permitido (só acréscimo, ROADMAP §1).
 */
export type AiErrorCode = 
/**  Bug: invariante quebrada sem código específico. */
"INTERNAL";

/**
 *  Erro devolvido por todo comando (`Result<T, AppError>`). A interface mostra a frase do
 *  catálogo para `code`, com `params`, e `detail` e `operationId` em "Detalhes técnicos".
 */
export type AppError = {
	/**  Código estável, por domínio. */
	code: ErrorCode,
	/**  Valores para a frase traduzida (nome do mod, versão…). */
	params: { [key in string]: string },
	/**
	 *  Evidência técnica (saída de ferramenta, status HTTP, caminho), sem segredos e com até
	 *  16 KB.
	 */
	detail: string | null,
	/**  Se repetir a mesma ação pode dar certo. */
	retryable: boolean,
	/**  Operação em que o erro aconteceu, quando houver. */
	operationId: OperationId | null,
};

/**  Códigos do domínio `app`. Só acréscimo. */
export type AppErrorCode = 
/**  Bug: todo `INTERNAL` visto em teste ou uso vira tarefa para um código específico. */
"INTERNAL" | 
/**  A operação pedida não existe (já terminou há muito tempo ou o id está errado). */
"OPERATION_NOT_FOUND" | 
/**  A operação não pode ser cancelada neste momento. */
"OPERATION_NOT_CANCELLABLE" | 
/**  Um valor das configurações foi recusado (`params.field` diz qual). */
"SETTINGS_INVALID" | 
/**  O `settings.json` foi gravado por uma versão mais nova do Warden; esta não o altera. */
"SETTINGS_NEWER_VERSION";

/**  Versão e commit do app em execução. */
export type AppInfo = {
	/**  Versão do app (a do `Cargo.toml` do workspace). */
	version: string,
	/**  Commit do código compilado (12 caracteres), quando conhecido. */
	commit: string | null,
	/**  Sistema em que o app roda. */
	platform: Platform,
	/**  Build de desenvolvimento (debug). */
	debugBuild: boolean,
};

/**  Onde as chaves ficam, gravado em `settings.json` como `secretsBackend`. */
export type BackendKind = 
/**  Cofre do sistema (padrão). */
"keyring" | 
/**  Arquivo `.env` na pasta de configuração do Warden. */
"envfile";

/**
 *  Códigos do domínio `bisect`. O código é contrato: renomear é mudança de contrato;
 *  acrescentar é permitido (só acréscimo, ROADMAP §1).
 */
export type BisectErrorCode = 
/**  Bug: invariante quebrada sem código específico. */
"INTERNAL";

/**
 *  Códigos do domínio `catalog`. O código é contrato: renomear é mudança de contrato;
 *  acrescentar é permitido (só acréscimo, ROADMAP §1).
 */
export type CatalogErrorCode = 
/**  Bug: invariante quebrada sem código específico. */
"INTERNAL";

/**
 *  Códigos do domínio `configs`. O código é contrato: renomear é mudança de contrato;
 *  acrescentar é permitido (só acréscimo, ROADMAP §1).
 */
export type ConfigsErrorCode = 
/**  Bug: invariante quebrada sem código específico. */
"INTERNAL" | 
/**  Arquivo grande demais para o editor estruturado. */
"TOO_LARGE" | 
/**  Arquivo que não é texto UTF-8. */
"NOT_UTF8" | 
/**  O texto não segue o formato esperado. */
"PARSE_FAILED" | 
/**  A chave pedida não existe no arquivo. */
"KEY_NOT_FOUND" | 
/**  A chave é uma seção, não um valor. */
"KEY_NOT_EDITABLE" | 
/**  O valor novo não serve para essa chave nesse formato. */
"INVALID_VALUE" | 
/**  A mesma chave apareceu duas vezes num pedido de edição. */
"DUPLICATE_EDIT" | 
/**  A releitura não confirmou a edição. */
"EDIT_NOT_CONFIRMED";

/**
 *  Códigos do domínio `core`, comuns a todas as crates. O código é contrato: renomear é
 *  mudança de contrato; acrescentar é permitido (só acréscimo, ROADMAP §1).
 */
export type CoreErrorCode = 
/**  Bug: invariante quebrada sem código específico. */
"INTERNAL" | 
/**  A operação foi cancelada pelo usuário. */
"CANCELLED" | 
/**  A operação passou do tempo-limite. */
"TIMEOUT" | 
/**  Falha ao ler ou gravar no disco. */
"IO" | 
/**  Um caminho vindo de fora tentou sair da pasta permitida. */
"PATH_OUTSIDE_ROOT" | 
/**  Sem conexão com a internet (ou o servidor não respondeu). */
"NETWORK_UNAVAILABLE";

/**
 *  Códigos do domínio `curseforge`. O código é contrato: renomear é mudança de contrato;
 *  acrescentar é permitido (só acréscimo, ROADMAP §1).
 */
export type CurseforgeErrorCode = 
/**  Bug: invariante quebrada sem código específico. */
"INTERNAL";

/**
 *  Códigos do domínio `diagnostics`. O código é contrato: renomear é mudança de contrato;
 *  acrescentar é permitido (só acréscimo, ROADMAP §1).
 */
export type DiagnosticsErrorCode = 
/**  Bug: invariante quebrada sem código específico. */
"INTERNAL" | 
/**  A pasta da sessão de teste não existe mais (podada ou apagada por fora). */
"SESSION_NOT_FOUND" | 
/**  Uma regra extra de redação não é uma expressão regular válida. */
"INVALID_REDACTION_RULE";

/**
 *  Códigos do domínio `discovery`. O código é contrato: renomear é mudança de contrato;
 *  acrescentar é permitido (só acréscimo, ROADMAP §1).
 */
export type DiscoveryErrorCode = 
/**  Bug: invariante quebrada sem código específico. */
"INTERNAL";

/**  Código de erro com o domínio: `{ "domain": "app", "code": "INTERNAL" }` no JSON. */
export type ErrorCode = 
/**  Erros do próprio app (`warden-app`). */
{ domain: "app"; code: AppErrorCode } | 
/**  Comuns a todos: cancelamento, tempo esgotado, disco, caminho fora da raiz, rede. */
{ domain: "core"; code: CoreErrorCode } | 
/**  Formato packwiz (`warden-packwiz`). */
{ domain: "packwiz"; code: PackwizErrorCode } | 
/**  Sidecar do packwiz (`warden-packwiz-cli`). */
{ domain: "packwizCli"; code: PackwizCliErrorCode } | 
/**  Serviço do pack (`warden-project`). */
{ domain: "project"; code: ProjectErrorCode } | 
/**  Metadados de jars (`warden-jarmeta`). */
{ domain: "jarmeta"; code: JarmetaErrorCode } | 
/**  API do Modrinth (`warden-modrinth`). */
{ domain: "modrinth"; code: ModrinthErrorCode } | 
/**  API da CurseForge (`warden-curseforge`). */
{ domain: "curseforge"; code: CurseforgeErrorCode } | 
/**  Catálogo de versões (`warden-catalog`). */
{ domain: "catalog"; code: CatalogErrorCode } | 
/**  Configs dos mods (`warden-configs`). */
{ domain: "configs"; code: ConfigsErrorCode } | 
/**  Java (`warden-java`). */
{ domain: "java"; code: JavaErrorCode } | 
/**  Launcher (`warden-launcher`). */
{ domain: "launcher"; code: LauncherErrorCode } | 
/**  Instância de teste (`warden-instance`). */
{ domain: "instance"; code: InstanceErrorCode } | 
/**  Diagnóstico (`warden-diagnostics`). */
{ domain: "diagnostics"; code: DiagnosticsErrorCode } | 
/**  IA (`warden-ai`). */
{ domain: "ai"; code: AiErrorCode } | 
/**  Versionamento (`warden-versioning`). */
{ domain: "versioning"; code: VersioningErrorCode } | 
/**  Exportação (`warden-export`). */
{ domain: "export"; code: ExportErrorCode } | 
/**  Chaves e tokens (`warden-secrets`). */
{ domain: "secrets"; code: SecretsErrorCode } | 
/**  Cliente HTTP (`warden-http`). */
{ domain: "http"; code: HttpErrorCode } | 
/**  Raio-x de mixins (`warden-mixin`; D4). */
{ domain: "mixin"; code: MixinErrorCode } | 
/**  Busca do culpado (`warden-bisect`; D4). */
{ domain: "bisect"; code: BisectErrorCode } | 
/**  Servidor local (`warden-server`; D4). */
{ domain: "server"; code: ServerErrorCode } | 
/**  Desempenho do jogo (`warden-perf`; D4). */
{ domain: "perf"; code: PerfErrorCode } | 
/**  Página de descoberta (`warden-discovery`; D4). */
{ domain: "discovery"; code: DiscoveryErrorCode } | 
/**  Importação (`warden-import`; D4). */
{ domain: "import"; code: ImportErrorCode } | 
/**  Scripts KubeJS e CraftTweaker (`warden-scripts`; D4). */
{ domain: "scripts"; code: ScriptsErrorCode };

/**
 *  Códigos do domínio `export`. O código é contrato: renomear é mudança de contrato;
 *  acrescentar é permitido (só acréscimo, ROADMAP §1).
 */
export type ExportErrorCode = 
/**  Bug: invariante quebrada sem código específico. */
"INTERNAL";

/**
 *  Códigos do domínio `http`. O código é contrato: renomear é mudança de contrato;
 *  acrescentar é permitido (só acréscimo, ROADMAP §1).
 */
export type HttpErrorCode = 
/**  Bug: invariante quebrada sem código específico. */
"INTERNAL" | 
/**  O servidor pediu para esperar (429) mais do que o Warden pode esperar sozinho. */
"RATE_LIMITED" | 
/**  O servidor respondeu com erro dele (5xx) mesmo depois das novas tentativas. */
"SERVER_ERROR" | 
/**  O endereço pedido não existe no servidor (404 ou 410). */
"NOT_FOUND" | 
/**  O servidor recusou o pedido com um código que o Warden não esperava. */
"UNEXPECTED_STATUS" | 
/**  A resposta veio num formato que o Warden não entende. */
"INVALID_RESPONSE" | 
/**  A resposta passou do tamanho máximo aceito. */
"RESPONSE_TOO_LARGE" | 
/**  O arquivo baixado não tem o hash esperado. */
"HASH_MISMATCH" | 
/**  O arquivo baixado não tem o tamanho esperado. */
"SIZE_MISMATCH" | 
/**  O link não pôde ser usado (não é http/https ou está malformado). */
"INVALID_URL" | 
/**  O servidor redirecionou vezes demais. */
"TOO_MANY_REDIRECTS" | 
/**  O servidor tentou redirecionar de https para http. */
"INSECURE_REDIRECT";

/**
 *  Códigos do domínio `import`. O código é contrato: renomear é mudança de contrato;
 *  acrescentar é permitido (só acréscimo, ROADMAP §1).
 */
export type ImportErrorCode = 
/**  Bug: invariante quebrada sem código específico. */
"INTERNAL";

/**
 *  Códigos do domínio `instance`. O código é contrato: renomear é mudança de contrato;
 *  acrescentar é permitido (só acréscimo, ROADMAP §1).
 */
export type InstanceErrorCode = 
/**  Bug: invariante quebrada sem código específico. */
"INTERNAL";

/**
 *  Códigos do domínio `jarmeta`. O código é contrato: renomear é mudança de contrato;
 *  acrescentar é permitido (só acréscimo, ROADMAP §1).
 */
export type JarmetaErrorCode = 
/**  Bug: invariante quebrada sem código específico. */
"INTERNAL" | 
/**  O arquivo não é um zip/jar válido (corrompido, truncado ou de outro formato). */
"INVALID_ARCHIVE" | 
/**  O jar passa de um limite de segurança (tamanho, número de entradas). */
"LIMIT_EXCEEDED";

/**
 *  Códigos do domínio `java`. O código é contrato: renomear é mudança de contrato;
 *  acrescentar é permitido (só acréscimo, ROADMAP §1).
 */
export type JavaErrorCode = 
/**  Bug: invariante quebrada sem código específico. */
"INTERNAL";

/**
 *  Códigos do domínio `launcher`. O código é contrato: renomear é mudança de contrato;
 *  acrescentar é permitido (só acréscimo, ROADMAP §1).
 */
export type LauncherErrorCode = 
/**  Bug: invariante quebrada sem código específico. */
"INTERNAL";

/**  Nível de detalhe dos registros (Configurações → Privacidade e registros). */
export type LogLevel = 
/**  `info` para tudo. */
"normal" | 
/**  `debug` para o código do Warden. */
"detailed";

/**
 *  Códigos do domínio `mixin`. O código é contrato: renomear é mudança de contrato;
 *  acrescentar é permitido (só acréscimo, ROADMAP §1).
 */
export type MixinErrorCode = 
/**  Bug: invariante quebrada sem código específico. */
"INTERNAL";

/**
 *  Códigos do domínio `modrinth`. O código é contrato: renomear é mudança de contrato;
 *  acrescentar é permitido (só acréscimo, ROADMAP §1).
 */
export type ModrinthErrorCode = 
/**  Bug: invariante quebrada sem código específico. */
"INTERNAL" | 
/**  O projeto não existe (ou não é público). */
"PROJECT_NOT_FOUND" | 
/**  A versão não existe. */
"VERSION_NOT_FOUND" | 
/**  O Modrinth não encontrou o endereço pedido. */
"NOT_FOUND" | 
/**  O Modrinth limitou as requisições (429) por mais tempo do que o Warden espera sozinho. */
"RATE_LIMITED" | 
/**  O Modrinth está fora do ar ou com erro (5xx). */
"UNAVAILABLE" | 
/**  O Modrinth recusou o pedido (4xx). */
"REQUEST_REJECTED" | 
/**  O Modrinth respondeu algo que o Warden não entende. */
"INVALID_RESPONSE" | 
/**  O cache local do Modrinth (`metadata.sqlite`) não pôde ser lido ou gravado. */
"CACHE_UNAVAILABLE";

/**  Identificador de uma operação longa no registro de operações (ARCHITECTURE §15). */
export type OperationId = string;

/**
 *  Tipo da operação, como chave estável (`"pack.create"`, `"test.start"`…). A interface usa
 *  para escolher o texto; cada tarefa define as suas constantes no próprio módulo.
 */
export type OperationKind = string;

/**  O que a interface sabe de uma operação. */
export type OperationSnapshot = {
	/**  Identificador. */
	id: OperationId,
	/**  Tipo. */
	kind: OperationKind,
	/**  Pack em que atua, se for o caso. */
	packId: PackId | null,
	/**  Situação. */
	state: OperationState,
	/**  Etapa atual. */
	stage: OperationStage | null,
	/**  Progresso da etapa atual. */
	progress: Progress | null,
	/**  Se "Cancelar" está disponível agora. */
	cancellable: boolean,
	/**  Início (milissegundos desde 1970, UTC). */
	startedAtMs: number,
	/**  Fim, quando terminou. */
	finishedAtMs: number | null,
	/**  Erro, quando terminou com erro. */
	error: AppError | null,
};

/**  Etapa atual. */
export type OperationStage = {
	/**  Identificador estável da etapa. */
	id: string,
	/**  Chave do texto no catálogo. */
	labelKey: string,
};

/**  Situação de uma operação. */
export type OperationState = 
/**  Em andamento. */
"running" | 
/**  Esperando outra operação no mesmo pack ("Aguardando outra operação neste pack"). */
"waitingForLock" | 
/**  Cancelamento pedido; ainda parando. */
"cancelling" | 
/**  Terminou bem. */
"succeeded" | 
/**  Terminou com erro. */
"failed" | 
/**  Cancelada. */
"cancelled";

/**
 *  `operation-updated`: uma operação mudou de estado, etapa ou progresso (painel Tarefas,
 *  T22).
 */
export type OperationUpdated = OperationSnapshot;

/**  Parte do pack que mudou, para a interface invalidar só o necessário. */
export type PackArea = 
/**  Mods, resource packs, shaders (lista do pack). */
"inventory" | 
/**  Configs. */
"configs" | 
/**  Informações do pack. */
"meta" | 
/**  Histórico de versões. */
"history";

/**  `pack-changed`: o pack mudou (escrita do Warden ou mudança externa). */
export type PackChanged = {
	/**  Pack alterado. */
	packId: PackId,
	/**  Partes alteradas. */
	areas: PackArea[],
};

/**
 *  Identificador de um pack: gerado na criação ou importação e gravado em
 *  `.warden/project.toml`. Todo comando que atua num pack o recebe como primeiro argumento
 *  (ARCHITECTURE §4.1).
 */
export type PackId = string;

/**
 *  Códigos do domínio `packwizCli`. O código é contrato: renomear é mudança de contrato;
 *  acrescentar é permitido (só acréscimo, ROADMAP §1).
 */
export type PackwizCliErrorCode = 
/**  Bug: invariante quebrada sem código específico. */
"INTERNAL" | 
/**  O executável do packwiz não foi encontrado. */
"BINARY_NOT_FOUND" | 
/**  O sistema não deixou iniciar o packwiz. */
"SPAWN_FAILED" | 
/**  A pasta não tem `pack.toml`. */
"PACK_FILE_MISSING" | 
/**  O packwiz terminou com erro (código de saída diferente de zero). */
"COMMAND_FAILED" | 
/**  O packwiz disse que deu certo, mas os arquivos relidos não conferem. */
"POSTCONDITION_FAILED" | 
/**
 *  O comando precisava da chave da CurseForge e ela não foi informada (mesmo texto do
 *  código da `warden-curseforge`, sem o `_` que o `CurseForge` geraria).
 */
"CURSEFORGE_KEY_MISSING" | 
/**  Há mods da CurseForge que só podem ser baixados à mão. */
"MANUAL_DOWNLOADS_REQUIRED" | 
/**  Um arquivo não pôde ser baixado e a exportação ficaria incompleta. */
"DOWNLOAD_FAILED" | 
/**  A pasta do pack tem um link simbólico ou junção, que o Warden não segue. */
"LINK_IN_PACK";

/**
 *  Códigos do domínio `packwiz`. O código é contrato: renomear é mudança de contrato;
 *  acrescentar é permitido (só acréscimo, ROADMAP §1).
 */
export type PackwizErrorCode = 
/**  Bug: invariante quebrada sem código específico. */
"INTERNAL" | 
/**  O arquivo não é um TOML válido. */
"INVALID_TOML" | 
/**  Um campo existe, mas com o tipo errado (texto onde se esperava número etc.). */
"INVALID_FIELD_TYPE" | 
/**  Um campo tem um valor que o packwiz não aceita (`pack-format` desconhecido etc.). */
"INVALID_FIELD_VALUE" | 
/**  Um caminho do índice ou de um metafile tenta sair da pasta do pack. */
"UNSAFE_PATH" | 
/**  Um link não pôde ser interpretado. */
"INVALID_URL" | 
/**  Formato de hash que o packwiz não conhece. */
"UNKNOWN_HASH_FORMAT";

/**
 *  Códigos do domínio `perf`. O código é contrato: renomear é mudança de contrato;
 *  acrescentar é permitido (só acréscimo, ROADMAP §1).
 */
export type PerfErrorCode = 
/**  Bug: invariante quebrada sem código específico. */
"INTERNAL";

/**  Sistema em que o app roda. */
export type Platform = 
/**  Windows (WebView2). */
"windows" | 
/**  Linux (WebKitGTK; só na CI). */
"linux" | 
/**  Outro (não suportado). */
"other";

/**  Quanto já foi feito. */
export type Progress = {
	/**  Quantidade feita. */
	current: number,
	/**  Total, quando conhecido. */
	total: number | null,
	/**  Unidade de `current` e `total`. */
	unit: ProgressUnit,
};

/**  Unidade do progresso, para a interface formatar o número. */
export type ProgressUnit = 
/**  Itens (mods, arquivos, etapas). */
"items" | 
/**  Bytes (downloads, cópias). */
"bytes";

/**
 *  Códigos do domínio `project`. O código é contrato: renomear é mudança de contrato;
 *  acrescentar é permitido (só acréscimo, ROADMAP §1).
 */
export type ProjectErrorCode = 
/**  Bug: invariante quebrada sem código específico. */
"INTERNAL";

/**
 *  Códigos do domínio `scripts`. O código é contrato: renomear é mudança de contrato;
 *  acrescentar é permitido (só acréscimo, ROADMAP §1).
 */
export type ScriptsErrorCode = 
/**  Bug: invariante quebrada sem código específico. */
"INTERNAL";

/**  Um segredo que o Warden guarda. Não existe "ler segredo" pela interface. */
export type SecretKind = 
/**  Chave da API da CurseForge. */
"curseforge" | 
/**  Chave da API do Gemini. */
"gemini" | 
/**  Token do GitHub (publicar versão). */
"github";

/**  Resultado de "Testar". */
export type SecretTestResult = 
/**  A API aceitou a chave. */
{ status: "valid" } | 
/**  Ainda não há como testar esta chave nesta versão. */
{ status: "notTestable" };

/**  Códigos do domínio `secrets` (ARCHITECTURE §5). Só acréscimo. */
export type SecretsErrorCode = 
/**  Bug. */
"INTERNAL" | 
/**
 *  O valor digitado não serve como chave (vazio, com quebra de linha, aspas simples ou
 *  longo demais).
 */
"INVALID_VALUE" | 
/**  A chave pedida não está configurada. */
"NOT_CONFIGURED" | 
/**  O cofre do sistema não está acessível (bloqueado, serviço parado, sem permissão). */
"VAULT_UNAVAILABLE" | 
/**  O cofre do sistema recusou a operação. */
"VAULT_FAILED" | 
/**  O arquivo `.env` existe mas não pôde ser lido como texto. */
"ENV_FILE_UNREADABLE" | 
/**  Depois de gravar, a releitura não trouxe o mesmo valor. */
"VERIFY_FAILED" | 
/**  A troca de modo falhou; as chaves continuam no modo anterior. */
"BACKEND_SWITCH_FAILED";

/**  O que a interface sabe das chaves: onde ficam e quais estão configuradas. */
export type SecretsStatus = {
	/**  Armazenamento em uso. */
	backend: BackendKind,
	/**  Chave da CurseForge configurada. */
	curseforge: boolean,
	/**  Chave do Gemini configurada. */
	gemini: boolean,
	/**  Token do GitHub configurado. */
	github: boolean,
};

/**
 *  Códigos do domínio `server`. O código é contrato: renomear é mudança de contrato;
 *  acrescentar é permitido (só acréscimo, ROADMAP §1).
 */
export type ServerErrorCode = 
/**  Bug: invariante quebrada sem código específico. */
"INTERNAL";

/**  Configurações do app. */
export type Settings = {
	/**  Versão do formato. */
	schemaVersion?: number,
	/**  Onde ficam as chaves (muda só por `secrets_backend_set`). */
	secretsBackend?: BackendKind,
	/**
	 *  Pasta padrão dos packs; `null` = a pasta padrão do sistema (Documentos\Warden).
	 *  Muda por um comando que abre o diálogo nativo (ARCHITECTURE §4.1), não por
	 *  `settings_update`.
	 */
	packsDir?: string | null,
	/**  Nome do jogador no perfil offline do teste. */
	playerName?: string,
	/**  Nível de detalhe dos registros. */
	logLevel?: LogLevel,
	/**  Mostrar diferenças antes de salvar uma config. */
	configDiffBeforeSave?: boolean,
	/**  Mostrar versões beta e alfa dos mods. */
	showPrereleaseVersions?: boolean,
	/**  Intervalo da verificação automática de atualizações, em horas (0 = desligada). */
	updateCheckIntervalHours?: number,
	/**  Memória padrão do teste. */
	testMemory?: TestMemory,
	/**  Quando a EULA do Minecraft foi aceita (RFC 3339), para o servidor local (P1, T27). */
	eulaAcceptedAt?: string | null,
};

/**  Mudanças pedidas pela interface (`settings_update`). Campo ausente = não muda. */
export type SettingsPatch = {
	/**
	 *  Nome do jogador: 3 a 16 caracteres, letras sem acento, números e `_` (regra do
	 *  Minecraft).
	 */
	playerName?: string | null,
	/**  Nível dos registros. */
	logLevel?: LogLevel | null,
	/**  Diferenças antes de salvar. */
	configDiffBeforeSave?: boolean | null,
	/**  Versões beta e alfa. */
	showPrereleaseVersions?: boolean | null,
	/**  Intervalo da verificação de atualizações (0 a 720 horas). */
	updateCheckIntervalHours?: number | null,
	/**  Memória do teste (512 a 65536 MB quando fixa). */
	testMemory?: TestMemory | null,
};

/**  Memória padrão do teste (Configurações → Teste). */
export type TestMemory = 
/**  O Warden escolhe pela quantidade de mods e pela memória do computador. */
{ mode: "auto" } | 
/**  Valor fixo, em MB. */
{ mode: "fixed"; 
/**  Memória máxima do Java, em MB. */
mb: number };

/**
 *  Códigos do domínio `versioning`. O código é contrato: renomear é mudança de contrato;
 *  acrescentar é permitido (só acréscimo, ROADMAP §1).
 */
export type VersioningErrorCode = 
/**  Bug: invariante quebrada sem código específico. */
"INTERNAL" | 
/**  A pasta do pack ainda não tem histórico de versões. */
"NOT_VERSIONED" | 
/**  A pasta do pack já tem histórico de versões. */
"ALREADY_VERSIONED" | 
/**  O histórico pertence a outro usuário do Windows (proteção da libgit2). */
"REPO_NOT_OWNED" | 
/**  Outro programa está mexendo no histórico agora (arquivo de trava do git). */
"REPO_LOCKED" | 
/**  O histórico está no meio de uma operação feita por fora (merge, rebase…). */
"REPO_BUSY" | 
/**  O histórico não está numa linha de versões (HEAD destacado). */
"DETACHED_HEAD" | 
/**  O histórico tem conflitos não resolvidos. */
"CONFLICTS" | 
/**  O texto não é uma versão no formato X.Y.Z. */
"INVALID_VERSION" | 
/**  A versão pedida não é maior que a última salva. */
"VERSION_NOT_GREATER" | 
/**  Já existe uma versão salva com esse número. */
"VERSION_EXISTS" | 
/**  Nada mudou desde a última versão salva. */
"NOTHING_CHANGED" | 
/**  A versão pedida não existe no histórico. */
"VERSION_NOT_FOUND" | 
/**  O ponto de segurança pedido não existe. */
"SAFETY_POINT_NOT_FOUND" | 
/**  A versão já foi publicada e não pode deixar de ser versão final. */
"VERSION_PUBLISHED" | 
/**  Um arquivo do pack está aberto em outro programa (o jogo, o antivírus…). */
"FILE_IN_USE" | 
/**  A restauração falhou e o pack não pôde voltar sozinho ao estado anterior. */
"ROLLBACK_FAILED" | 
/**  Falha da biblioteca git ao ler ou gravar o histórico. */
"GIT_FAILED";

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

