// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	/**  Informa a versão, o commit e a plataforma do app. */
	appInfo: () => typedError<AppInfo, AppError>(__TAURI_INVOKE("app_info")),
	/**  Configurações atuais. */
	settingsGet: () => typedError<Settings, AppError>(__TAURI_INVOKE("settings_get")),
	/**  Altera as configurações e devolve como ficaram. O nível dos registros vale na hora. */
	settingsUpdate: (patch: SettingsPatch) => typedError<Settings, AppError>(__TAURI_INVOKE("settings_update", { patch })),
	/**  Operações em andamento e as últimas concluídas (painel Tarefas). */
	operationsList: () => typedError<OperationSnapshot[], AppError>(__TAURI_INVOKE("operations_list")),
	/**  Pede o cancelamento de uma operação. */
	operationCancel: (operationId: OperationId) => typedError<null, AppError>(__TAURI_INVOKE("operation_cancel", { operationId })),
	/**  Onde as chaves ficam e quais estão configuradas. */
	secretsStatus: () => typedError<SecretsStatus, AppError>(__TAURI_INVOKE("secrets_status")),
	/**  Grava uma chave digitada e devolve o estado. */
	secretsSet: (kind: SecretKind, value: string) => typedError<SecretsStatus, AppError>(__TAURI_INVOKE("secrets_set", { kind, value })),
	/**  Testa uma chave na API dela. */
	secretsTest: (kind: SecretKind) => typedError<SecretTestResult, AppError>(__TAURI_INVOKE("secrets_test", { kind })),
	/**  Apaga uma chave e devolve o estado. */
	secretsRemove: (kind: SecretKind) => typedError<SecretsStatus, AppError>(__TAURI_INVOKE("secrets_remove", { kind })),
	/**  Modo das chaves em uso. */
	secretsBackendGet: () => typedError<BackendKind, AppError>(__TAURI_INVOKE("secrets_backend_get")),
	/**  Troca o modo das chaves (cofre ↔ `.env`), movendo-as, e devolve o estado. */
	secretsBackendSet: (backend: BackendKind) => typedError<SecretsStatus, AppError>(__TAURI_INVOKE("secrets_backend_set", { backend })),
	/**
	 *  As versões do Minecraft, na ordem oficial do manifesto da Mojang (da mais nova para a mais
	 *  antiga), com o tipo de cada uma e a etiqueta "melhor esforço" antes da 1.7.10.
	 */
	catalogMinecraftVersions: (forceRefresh: boolean) => typedError<MinecraftVersions, AppError>(__TAURI_INVOKE("catalog_minecraft_versions", { forceRefresh })),
	/**
	 *  As versões de um loader para uma versão do Minecraft, da mais nova para a mais antiga, com
	 *  a pré-selecionada. Lista vazia: o loader não existe para essa versão.
	 */
	catalogLoaderVersions: (loader: Loader, minecraft: string, forceRefresh: boolean) => typedError<LoaderVersions, AppError>(__TAURI_INVOKE("catalog_loader_versions", { loader, minecraft, forceRefresh })),
	/**  O Java que o teste do pack vai usar e por quê (ADR-0029). */
	javaChoice: (request: JavaChoiceRequest) => typedError<JavaChoice, AppError>(__TAURI_INVOKE("java_choice", { request })),
	/**  A tabela de Java de Configurações. */
	javaRuntimesList: () => typedError<JavaOverview, AppError>(__TAURI_INVOKE("java_runtimes_list")),
	/**
	 *  "Procurar atualizações do Java": instala a atualização mais nova de cada Java instalado e
	 *  remove as antigas que nenhum jogo usa.
	 */
	javaRuntimesCheckUpdates: () => typedError<UpdateReport, AppError>(__TAURI_INVOKE("java_runtimes_check_updates")),
	/**  Remove um Java e devolve a tabela atualizada. */
	javaRuntimeRemove: (id: RuntimeId) => typedError<JavaOverview, AppError>(__TAURI_INVOKE("java_runtime_remove", { id })),
	/**  "Remover Javas sem uso" e devolve a tabela atualizada. */
	javaRuntimesRemoveUnused: () => typedError<JavaOverview, AppError>(__TAURI_INVOKE("java_runtimes_remove_unused")),
	/**  Lista de packs registrados, inclusive pastas perdidas e manifestos inválidos. */
	packsList: () => __TAURI_INVOKE<PackRow[]>("packs_list"),
	/**  Dados de um pack da lista. */
	packGet: (packId: PackId) => typedError<PackRow, AppError>(__TAURI_INVOKE("pack_get", { packId })),
	/**  Cria um pack vazio com versões confirmadas pelo catálogo e ponto inicial no histórico. */
	packCreate: (request: CreatePack) => typedError<CreatedPack, AppError>(__TAURI_INVOKE("pack_create", { request })),
	/**  Verifica uma pasta packwiz sem escrever nela. */
	packImportPreview: (path: string) => typedError<ImportPreview, AppError>(__TAURI_INVOKE("pack_import_preview", { path })),
	/**  Abre e registra uma pasta packwiz. `add_controls` aceita os arquivos de controle padrão. */
	packImport: (path: string, addControls: boolean) => typedError<ImportedPack, AppError>(__TAURI_INVOKE("pack_import", { path, addControls })),
	/**  Localiza a nova pasta de um pack perdido sem trocar seu histórico local. */
	packRelocate: (packId: PackId, path: string) => typedError<null, AppError>(__TAURI_INVOKE("pack_relocate", { packId, path })),
	/**  Retira apenas do registro local. */
	packForget: (packId: PackId) => typedError<null, AppError>(__TAURI_INVOKE("pack_forget", { packId })),
	/**  Itens que não devem entrar no pack distribuído. */
	packHygieneScan: (packId: PackId) => typedError<HygieneFinding[], AppError>(__TAURI_INVOKE("pack_hygiene_scan", { packId })),
	/**  Remove os itens escolhidos após criar ponto de segurança. */
	packHygieneFix: (packId: PackId, paths: string[]) => typedError<string[], AppError>(__TAURI_INVOKE("pack_hygiene_fix", { packId, paths })),
	/**  Move um pack para a Lixeira depois de digitar o nome exato. */
	packTrash: (packId: PackId, confirmation: string) => typedError<null, AppError>(__TAURI_INVOKE("pack_trash", { packId, confirmation })),
	/**  Lista exata da saída e avisos antes de exportar. */
	exportPreview: (packId: PackId, source: ExportSource) => typedError<ExportPreview, AppError>(__TAURI_INVOKE("export_preview", { packId, source })),
	/**  Adiciona uma regra ao `.packwizignore` e atualiza o índice. */
	exportExclude: (packId: PackId, path: string) => typedError<null, AppError>(__TAURI_INVOKE("export_exclude", { packId, path })),
	/**  Abre o diálogo nativo e gera a saída. `None` significa cancelamento do diálogo. */
	exportRun: (packId: PackId, source: ExportSource, format: ExportFormat) => typedError<{
	/**  Pasta ou arquivo escolhido no diálogo nativo. */
	path: string,
	/**  Arquivos distribuídos, em ordem. */
	files: string[],
	/**  Bytes da saída final (zip comprimido ou soma dos arquivos). */
	bytes: number,
} | null, AppError>(__TAURI_INVOKE("export_run", { packId, source, format })),
	/**  Primeira execução e pasta dos packs em uso. */
	settingsStatus: () => typedError<SettingsStatus, AppError>(__TAURI_INVOKE("settings_status")),
	/**
	 *  Abre o diálogo nativo de pasta, valida a escolhida e a grava como pasta dos packs
	 *  (ARCHITECTURE §4.1: o caminho não vem da interface). `null` = o usuário desistiu.
	 */
	settingsChoosePacksDir: () => typedError<{
	/**  O `settings.json` ainda não existe: o app abre na primeira execução (T01). */
	firstRun: boolean,
	/**  Pasta onde os packs novos são criados (a escolhida ou a padrão do sistema). */
	packsDir: string,
	/**  Pasta padrão do sistema (Documentos\Warden). */
	defaultPacksDir: string,
} | null, AppError>(__TAURI_INVOKE("settings_choose_packs_dir")),
	/**  Abre a pasta dos registros no Explorador (Configurações → Privacidade e registros). */
	logsRevealFolder: () => typedError<null, AppError>(__TAURI_INVOKE("logs_reveal_folder")),
	/**
	 *  Informa onde está o botão maximizar da barra de título, para a janela nativa do menu de
	 *  encaixe (Snap Layouts) ficar exatamente em cima dele. No Linux a barra é a do sistema e o
	 *  comando não faz nada.
	 */
	windowSetMaximizeArea: (area: MaximizeButtonArea) => typedError<null, AppError>(__TAURI_INVOKE("window_set_maximize_area", { area })),
	/**  Autor e pasta padrão do assistente Criar pack. */
	packCreateDefaults: () => __TAURI_INVOKE<CreateDefaults>("pack_create_defaults"),
	/**
	 *  Etapa "Nome e pasta": confere o nome e devolve a pasta final, recusando pasta com arquivos
	 *  antes de qualquer escrita (CA-T03-04). `destination` vazio = `<pasta dos packs>/<nome>`.
	 */
	packCreateCheck: (name: string, destination: string | null) => typedError<string, AppError>(__TAURI_INVOKE("pack_create_check", { name, destination })),
	/**
	 *  Abre o diálogo nativo de pasta (ARCHITECTURE §20: diálogos são do Rust). `null` = o usuário
	 *  desistiu. O caminho escolhido ainda passa pelas validações do comando que o usa.
	 */
	packChooseFolder: (purpose: FolderPurpose) => typedError<string | null, AppError>(__TAURI_INVOKE("pack_choose_folder", { purpose })),
	/**  "Mostrar na pasta": abre o Explorador com a pasta do pack selecionada. */
	packRevealFolder: (packId: PackId) => typedError<null, AppError>(__TAURI_INVOKE("pack_reveal_folder", { packId })),
};

/** Events */
export const events = {
	operationUpdated: makeEvent<OperationUpdated>("operation-updated"),
	packChanged: makeEvent<PackChanged>("pack-changed"),
	titleBarMaximize: makeEvent<TitleBarMaximize>("title-bar-maximize"),
};

/* Types */
/**
 *  Códigos do domínio `ai`. O código é contrato: renomear é mudança de contrato;
 *  acrescentar é permitido (só acréscimo, ROADMAP §1).
 */
export type AiErrorCode = 
/**  Bug: invariante quebrada sem código específico. */
"INTERNAL";

/**
 *  Erro devolvido por todo comando (`Result<T, AppError>`). A interface mostra a frase do
 *  catálogo para `code`, com `params`, e `detail` e `operationId` em "Detalhes técnicos".
 */
export type AppError = {
	/**  Código estável, por domínio. */
	code: ErrorCode,
	/**  Valores para a frase traduzida (nome do mod, versão…). */
	params: { [key in string]: string },
	/**
	 *  Evidência técnica (saída de ferramenta, status HTTP, caminho), sem segredos e com até
	 *  16 KB.
	 */
	detail: string | null,
	/**  Se repetir a mesma ação pode dar certo. */
	retryable: boolean,
	/**  Operação em que o erro aconteceu, quando houver. */
	operationId: OperationId | null,
};

/**  Códigos do domínio `app`. Só acréscimo. */
export type AppErrorCode = 
/**  Bug: todo `INTERNAL` visto em teste ou uso vira tarefa para um código específico. */
"INTERNAL" | 
/**  A operação pedida não existe (já terminou há muito tempo ou o id está errado). */
"OPERATION_NOT_FOUND" | 
/**  A operação não pode ser cancelada neste momento. */
"OPERATION_NOT_CANCELLABLE" | 
/**  Um valor das configurações foi recusado (`params.field` diz qual). */
"SETTINGS_INVALID" | 
/**  O `settings.json` foi gravado por uma versão mais nova do Warden; esta não o altera. */
"SETTINGS_NEWER_VERSION";

/**  Versão e commit do app em execução. */
export type AppInfo = {
	/**  Versão do app (a do `Cargo.toml` do workspace). */
	version: string,
	/**  Commit do código compilado (12 caracteres), quando conhecido. */
	commit: string | null,
	/**  Sistema em que o app roda. */
	platform: Platform,
	/**  Build de desenvolvimento (debug). */
	debugBuild: boolean,
};

/**  Onde as chaves ficam, gravado em `settings.json` como `secretsBackend`. */
export type BackendKind = 
/**  Cofre do sistema (padrão). */
"keyring" | 
/**  Arquivo `.env` na pasta de configuração do Warden. */
"envfile";

/**
 *  Códigos do domínio `bisect`. O código é contrato: renomear é mudança de contrato;
 *  acrescentar é permitido (só acréscimo, ROADMAP §1).
 */
export type BisectErrorCode = 
/**  Bug: invariante quebrada sem código específico. */
"INTERNAL";

/**
 *  Códigos do domínio `catalog`. O código é contrato: renomear é mudança de contrato;
 *  acrescentar é permitido (só acréscimo, ROADMAP §1).
 */
export type CatalogErrorCode = 
/**  Bug: invariante quebrada sem código específico. */
"INTERNAL" | 
/**  A fonte (`params.source`) está fora do ar ou com erro (5xx) e não há lista no cache. */
"SOURCE_UNAVAILABLE" | 
/**  A fonte limitou as requisições (429) por mais tempo do que o Warden espera sozinho. */
"RATE_LIMITED" | 
/**  A fonte recusou o pedido ou não achou o endereço (4xx). */
"REQUEST_REJECTED" | 
/**  A fonte respondeu algo que o Warden não entende. */
"INVALID_RESPONSE" | 
/**  A versão do Minecraft (`params.id`) não existe no manifesto da Mojang. */
"VERSION_NOT_FOUND" | 
/**  O JSON da versão baixado não bate com o `sha1` do manifesto (`params.id`). */
"VERSION_JSON_CORRUPTED" | 
/**  O cache local do catálogo (`metadata.sqlite`) não pôde ser lido ou gravado. */
"CACHE_UNAVAILABLE";

/**
 *  Códigos do domínio `configs`. O código é contrato: renomear é mudança de contrato;
 *  acrescentar é permitido (só acréscimo, ROADMAP §1).
 */
export type ConfigsErrorCode = 
/**  Bug: invariante quebrada sem código específico. */
"INTERNAL" | 
/**  Arquivo grande demais para o editor estruturado. */
"TOO_LARGE" | 
/**  Arquivo que não é texto UTF-8. */
"NOT_UTF8" | 
/**  O texto não segue o formato esperado. */
"PARSE_FAILED" | 
/**  A chave pedida não existe no arquivo. */
"KEY_NOT_FOUND" | 
/**  A chave é uma seção, não um valor. */
"KEY_NOT_EDITABLE" | 
/**  O valor novo não serve para essa chave nesse formato. */
"INVALID_VALUE" | 
/**  A mesma chave apareceu duas vezes num pedido de edição. */
"DUPLICATE_EDIT" | 
/**  A releitura não confirmou a edição. */
"EDIT_NOT_CONFIRMED";

/**  Mudança proposta em um arquivo de controle, apresentada antes de aplicar. */
export type ControlDiff = {
	/**  Caminho relativo. */
	path: string,
	/**  Conteúdo atual, ou `null` se não existe. */
	current: string | null,
	/**  Conteúdo proposto, preservando padrões adicionais do usuário. */
	suggested: string,
};

/**
 *  Códigos do domínio `core`, comuns a todas as crates. O código é contrato: renomear é
 *  mudança de contrato; acrescentar é permitido (só acréscimo, ROADMAP §1).
 */
export type CoreErrorCode = 
/**  Bug: invariante quebrada sem código específico. */
"INTERNAL" | 
/**  A operação foi cancelada pelo usuário. */
"CANCELLED" | 
/**  A operação passou do tempo-limite. */
"TIMEOUT" | 
/**  Falha ao ler ou gravar no disco. */
"IO" | 
/**  Um caminho vindo de fora tentou sair da pasta permitida. */
"PATH_OUTSIDE_ROOT" | 
/**  Sem conexão com a internet (ou o servidor não respondeu). */
"NETWORK_UNAVAILABLE";

/**  O que o assistente Criar pack mostra antes de o usuário digitar (SPEC T03, etapa 1). */
export type CreateDefaults = {
	/**  Autor padrão: o nome do jogador configurado. */
	author: string,
	/**  Pasta onde os packs novos são criados. */
	packsDir: string,
};

/**  Pedido final do assistente de criação. Mods iniciais são acrescentados pela P1-18. */
export type CreatePack = {
	/**  Nome, de 1 a 64 caracteres. */
	name: string,
	/**  Autor. */
	author: string,
	/**  Descrição opcional. */
	description: string,
	/**  Pasta escolhida; vazia significa usar a pasta padrão e o slug do nome. */
	destination: string | null,
	/**  Id exato do manifesto da Mojang. */
	minecraft: string,
	/**  `None` = vanilla. */
	loader: Loader | null,
	/**  Versão exata do loader, obrigatória se houver loader. */
	loaderVersion: string | null,
};

/**  Resultado de uma criação. */
export type CreatedPack = {
	/**  Identificador estável. */
	id: PackId,
	/**  Pasta final. */
	path: string,
};

/**
 *  Códigos do domínio `curseforge`. O código é contrato: renomear é mudança de contrato;
 *  acrescentar é permitido (só acréscimo, ROADMAP §1).
 */
export type CurseforgeErrorCode = 
/**  Bug: invariante quebrada sem código específico. */
"INTERNAL" | 
/**  Não há chave da CurseForge configurada; nenhuma requisição foi feita. */
"CURSEFORGE_KEY_MISSING" | 
/**  A CurseForge recusou a chave (401 ou 403 da API). */
"CURSEFORGE_KEY_INVALID" | 
/**  O projeto (mod, resource pack, shader…) não existe ou não está disponível. */
"MOD_NOT_FOUND" | 
/**  O arquivo não existe ou não está disponível. */
"FILE_NOT_FOUND" | 
/**  O autor não deixa apps de terceiros baixarem o arquivo (distribuição bloqueada). */
"DISTRIBUTION_BLOCKED" | 
/**  A busca passou dos limites da API (página, 10 mil resultados, filtros demais). */
"INVALID_QUERY" | 
/**  A CurseForge não encontrou o endereço pedido. */
"NOT_FOUND" | 
/**  A CurseForge limitou as requisições (429) por mais tempo do que o Warden espera sozinho. */
"RATE_LIMITED" | 
/**  A CurseForge está fora do ar ou com erro (5xx). */
"UNAVAILABLE" | 
/**  A CurseForge recusou o pedido (4xx que não é de chave). */
"REQUEST_REJECTED" | 
/**  A CurseForge respondeu algo que o Warden não entende. */
"INVALID_RESPONSE";

/**
 *  Códigos do domínio `diagnostics`. O código é contrato: renomear é mudança de contrato;
 *  acrescentar é permitido (só acréscimo, ROADMAP §1).
 */
export type DiagnosticsErrorCode = 
/**  Bug: invariante quebrada sem código específico. */
"INTERNAL" | 
/**  A pasta da sessão de teste não existe mais (podada ou apagada por fora). */
"SESSION_NOT_FOUND" | 
/**  Uma regra extra de redação não é uma expressão regular válida. */
"INVALID_REDACTION_RULE";

/**
 *  Códigos do domínio `discovery`. O código é contrato: renomear é mudança de contrato;
 *  acrescentar é permitido (só acréscimo, ROADMAP §1).
 */
export type DiscoveryErrorCode = 
/**  Bug: invariante quebrada sem código específico. */
"INTERNAL";

/**  Código de erro com o domínio: `{ "domain": "app", "code": "INTERNAL" }` no JSON. */
export type ErrorCode = 
/**  Erros do próprio app (`warden-app`). */
{ domain: "app"; code: AppErrorCode } | 
/**  Comuns a todos: cancelamento, tempo esgotado, disco, caminho fora da raiz, rede. */
{ domain: "core"; code: CoreErrorCode } | 
/**  Formato packwiz (`warden-packwiz`). */
{ domain: "packwiz"; code: PackwizErrorCode } | 
/**  Sidecar do packwiz (`warden-packwiz-cli`). */
{ domain: "packwizCli"; code: PackwizCliErrorCode } | 
/**  Serviço do pack (`warden-project`). */
{ domain: "project"; code: ProjectErrorCode } | 
/**  Metadados de jars (`warden-jarmeta`). */
{ domain: "jarmeta"; code: JarmetaErrorCode } | 
/**  API do Modrinth (`warden-modrinth`). */
{ domain: "modrinth"; code: ModrinthErrorCode } | 
/**  API da CurseForge (`warden-curseforge`). */
{ domain: "curseforge"; code: CurseforgeErrorCode } | 
/**  Catálogo de versões (`warden-catalog`). */
{ domain: "catalog"; code: CatalogErrorCode } | 
/**  Configs dos mods (`warden-configs`). */
{ domain: "configs"; code: ConfigsErrorCode } | 
/**  Java (`warden-java`). */
{ domain: "java"; code: JavaErrorCode } | 
/**  Launcher (`warden-launcher`). */
{ domain: "launcher"; code: LauncherErrorCode } | 
/**  Instância de teste (`warden-instance`). */
{ domain: "instance"; code: InstanceErrorCode } | 
/**  Diagnóstico (`warden-diagnostics`). */
{ domain: "diagnostics"; code: DiagnosticsErrorCode } | 
/**  IA (`warden-ai`). */
{ domain: "ai"; code: AiErrorCode } | 
/**  Versionamento (`warden-versioning`). */
{ domain: "versioning"; code: VersioningErrorCode } | 
/**  Exportação (`warden-export`). */
{ domain: "export"; code: ExportErrorCode } | 
/**  Chaves e tokens (`warden-secrets`). */
{ domain: "secrets"; code: SecretsErrorCode } | 
/**  Cliente HTTP (`warden-http`). */
{ domain: "http"; code: HttpErrorCode } | 
/**  Raio-x de mixins (`warden-mixin`; D4). */
{ domain: "mixin"; code: MixinErrorCode } | 
/**  Busca do culpado (`warden-bisect`; D4). */
{ domain: "bisect"; code: BisectErrorCode } | 
/**  Servidor local (`warden-server`; D4). */
{ domain: "server"; code: ServerErrorCode } | 
/**  Desempenho do jogo (`warden-perf`; D4). */
{ domain: "perf"; code: PerfErrorCode } | 
/**  Página de descoberta (`warden-discovery`; D4). */
{ domain: "discovery"; code: DiscoveryErrorCode } | 
/**  Importação (`warden-import`; D4). */
{ domain: "import"; code: ImportErrorCode } | 
/**  Scripts KubeJS e CraftTweaker (`warden-scripts`; D4). */
{ domain: "scripts"; code: ScriptsErrorCode };

/**  Motivo de um alerta da prévia; a interface escolhe o texto exibido. */
export type ExportAlert = 
/**  Arquivo distribuído com mais de 20 MiB. */
{ kind: "largeFile" } | 
/**  `options.txt` sem `preserve` pode sobrescrever as preferências do jogador. */
{ kind: "optionsOverridesPreferences" } | 
/**  Arquivo distribuído diretamente na raiz do pack. */
{ kind: "looseRootFile" } | 
/**  Motivo identificado pela varredura de higiene do pack. */
{ kind: "hygiene"; 
/**  Causa original da higiene. */
cause: HygieneCause };

/**
 *  Códigos do domínio `export`. O código é contrato: renomear é mudança de contrato;
 *  acrescentar é permitido (só acréscimo, ROADMAP §1).
 */
export type ExportErrorCode = 
/**  Bug: invariante quebrada sem código específico. */
"INTERNAL";

/**  Saída nativa. */
export type ExportFormat = 
/**  Diretório com a árvore do pack. */
"folder" | 
/**  Arquivo ZIP com a mesma árvore. */
"zip";

/**  Prévia lida dos mesmos bytes que a exportação vai considerar. */
export type ExportPreview = {
	/**  Arquivos exatos da saída (inclusive manifesto e índice). */
	files: PreviewFile[],
	/**  Pastas da árvore, com seus totais. */
	folders: PreviewFolder[],
	/**  Total de bytes dos arquivos da lista. */
	bytes: number,
	/**  Número de referências a mods/resource packs/shaders. */
	references: number,
	/**  Conferências e avisos. */
	preflight: Preflight,
};

/**  Resultado persistido. */
export type ExportResult = {
	/**  Pasta ou arquivo escolhido no diálogo nativo. */
	path: string,
	/**  Arquivos distribuídos, em ordem. */
	files: string[],
	/**  Bytes da saída final (zip comprimido ou soma dos arquivos). */
	bytes: number,
};

/**  Origem da exportação. Uma versão salva nunca lê a árvore de trabalho. */
export type ExportSource = 
/**  Estado atual do pack. */
{ kind: "current" } | 
/**  Tag `v<version>` validada por `warden-versioning`. */
{ kind: "saved"; 
/**  Número `SemVer` sem o prefixo `v`. */
version: string };

/**  Para que a pasta está sendo escolhida: decide o título do diálogo e onde ele abre. */
export type FolderPurpose = 
/**  Pasta de um pack novo (Criar pack). */
"createDestination" | 
/**  Pasta packwiz existente (Abrir ou importar…). */
"openPack" | 
/**  Nova pasta de um pack que sumiu (Localizar…). */
"relocate";

/**
 *  De quando é a lista e se veio do cache porque a fonte não respondeu (SPEC T03: "Lista de
 *  versões de <data>").
 */
export type Freshness = {
	/**
	 *  Quando a lista foi baixada da fonte (milissegundos desde 1970, UTC). Numa lista
	 *  montada de várias respostas, a mais antiga.
	 */
	fetchedAtMs: number,
	/**
	 *  `true` quando a fonte não respondeu (sem internet, fora do ar) e o catálogo usou o que
	 *  estava guardado, mesmo vencido. A interface mostra a data.
	 */
	offline: boolean,
};

/**
 *  Códigos do domínio `http`. O código é contrato: renomear é mudança de contrato;
 *  acrescentar é permitido (só acréscimo, ROADMAP §1).
 */
export type HttpErrorCode = 
/**  Bug: invariante quebrada sem código específico. */
"INTERNAL" | 
/**  O servidor pediu para esperar (429) mais do que o Warden pode esperar sozinho. */
"RATE_LIMITED" | 
/**  O servidor respondeu com erro dele (5xx) mesmo depois das novas tentativas. */
"SERVER_ERROR" | 
/**  O endereço pedido não existe no servidor (404 ou 410). */
"NOT_FOUND" | 
/**  O servidor recusou o pedido com um código que o Warden não esperava. */
"UNEXPECTED_STATUS" | 
/**  A resposta veio num formato que o Warden não entende. */
"INVALID_RESPONSE" | 
/**  A resposta passou do tamanho máximo aceito. */
"RESPONSE_TOO_LARGE" | 
/**  O arquivo baixado não tem o hash esperado. */
"HASH_MISMATCH" | 
/**  O arquivo baixado não tem o tamanho esperado. */
"SIZE_MISMATCH" | 
/**  O link não pôde ser usado (não é http/https ou está malformado). */
"INVALID_URL" | 
/**  O servidor redirecionou vezes demais. */
"TOO_MANY_REDIRECTS" | 
/**  O servidor tentou redirecionar de https para http. */
"INSECURE_REDIRECT";

/**  Motivo de um item da higiene, sem texto: a frase fica no catálogo da interface. */
export type HygieneCause = 
/**  Casa com uma linha do modelo do Warden. */
{ kind: "pattern"; 
/**  A linha do modelo. */
pattern: string; 
/**  O grupo da linha. */
group: HygieneGroup } | 
/**  Item na raiz que não é arquivo de controle nem pasta de conteúdo conhecida. */
{ kind: "unknownRootItem" } | 
/**  Arquivo grande que não é jar. */
{ kind: "largeFile" } | 
/**  Pasta desconhecida com muitos arquivos. */
{ kind: "cacheLikeFolder"; 
/**  Quantos arquivos ela tem. */
files: number } | 
/**  Link simbólico ou junção. */
{ kind: "symlink" };

/**  Item da higiene, pronto para o IPC. */
export type HygieneFinding = {
	/**  Caminho relativo. */
	path: string,
	/**  Pasta inteira. */
	isDir: boolean,
	/**  Existe no disco. */
	onDisk: boolean,
	/**  Está no índice distribuído. */
	inIndex: boolean,
	/**  Tamanho no disco em bytes (a soma dos arquivos, numa pasta); `0` fora do disco. */
	bytes: number | null,
	/**  Por que foi apontado; a interface escreve a frase. */
	reasons: HygieneCause[],
};

/**  Grupo do padrão do modelo que apontou o item (ARCHITECTURE §6.4). */
export type HygieneGroup = 
/**  Bloco obrigatório (arquivos do próprio Warden). */
"required" | 
/**  Dados de execução do jogo e do launcher. */
"runtime" | 
/**  Segredos e arquivos de ferramentas. */
"secretsAndTools" | 
/**  Dados de servidor e do instalador. */
"serverOnly" | 
/**  Lixo em qualquer profundidade. */
"anyDepth";

/**
 *  Códigos do domínio `import`. O código é contrato: renomear é mudança de contrato;
 *  acrescentar é permitido (só acréscimo, ROADMAP §1).
 */
export type ImportErrorCode = 
/**  Bug: invariante quebrada sem código específico. */
"INTERNAL";

/**  Diagnóstico de uma pasta antes de importar, sem alterações no disco. */
export type ImportPreview = {
	/**  Pasta proposta. */
	path: string,
	/**  Nome do pack. */
	name: string,
	/**  Minecraft. */
	minecraft: string | null,
	/**  Loader ou `null` para vanilla. */
	loader: string | null,
	/**  Arquivos que a higiene propõe limpar, com tamanho e motivo (SPEC T04, passo 3). */
	hygiene: HygieneFinding[],
	/**  Controles padrão ausentes; o bloco obrigatório é aplicado sempre. */
	missingControls: string[],
	/**  Proposta para cada arquivo de controle ausente ou diferente. */
	controlDiffs: ControlDiff[],
	/**  Git existente em estado que impede alterações. */
	readOnlyReason: string | null,
};

/**  Resultado da importação. */
export type ImportedPack = {
	/**  Identificador registrado. */
	id: PackId,
	/**  Pasta registrada. */
	path: string,
	/**  Um ID de uma cópia foi substituído. */
	copiedIdReplaced: boolean,
	/**  Linhas acrescentadas ao bloco obrigatório. */
	requiredIgnoreAdded: string[],
	/**  Estado somente leitura do git. */
	readOnlyReason: string | null,
};

/**  Um Java instalado pelo Warden. */
export type InstalledRuntime = {
	/**  Identificador (nome da pasta). */
	id: RuntimeId,
	/**  Fonte. */
	source: RuntimeSource,
	/**  Versão, conferida executando o Java. */
	version: JavaVersion,
	/**  `java.vendor` informado pelo próprio Java ("Eclipse Adoptium", "Oracle Corporation"…). */
	vendor: string,
	/**  Nome da versão na fonte (`jdk-21.0.12.1+1`, `8u51-cacert462b08`). */
	releaseName: string,
	/**  Processador (`x64`). */
	arch: string,
	/**  Pasta do Java. */
	home: string,
	/**  Programa que abre o jogo (`javaw.exe` no Windows, `java` no Linux). */
	launcher: string,
	/**  Programa `java` com console (validação). */
	java: string,
	/**  Quando foi instalado (milissegundos desde 1970). */
	installedAtMs: number,
	/**  Teto de atualização do canal (o `312` de "8 ≤ u312"); as atualizações respeitam o teto. */
	updateCap: number | null,
	/**  Componente da Mojang (`java-runtime-delta`), quando a fonte é a Mojang. */
	mojangComponent: string | null,
	/**  SHA-256 do pacote baixado (Temurin). */
	archiveSha256: string | null,
	/**
	 *  Java mais novo que substituiu este numa atualização; ele é removido quando nenhum jogo
	 *  o estiver usando.
	 */
	supersededBy: RuntimeId | null,
};

/**
 *  Códigos do domínio `instance`. O código é contrato: renomear é mudança de contrato;
 *  acrescentar é permitido (só acréscimo, ROADMAP §1).
 */
export type InstanceErrorCode = 
/**  Bug: invariante quebrada sem código específico. */
"INTERNAL" | 
/**  O `pack.toml` ou o `index.toml` do pack não puderam ser lidos. */
"PACK_UNREADABLE" | 
/**  O `pack.toml` não diz a versão do Minecraft. */
"MINECRAFT_VERSION_MISSING" | 
/**  O `pack.toml` não fixa a versão exata do loader (D7). */
"LOADER_VERSION_NOT_EXACT" | 
/**  O `pack.toml` tem mais de um loader. */
"LOADER_AMBIGUOUS" | 
/**  Alguns itens do pack não foram copiados para a instância. */
"SYNC_INCOMPLETE" | 
/**  O arquivo escolhido para um download manual não é o esperado (hash diferente). */
"MANUAL_FILE_MISMATCH" | 
/**  O cache de downloads (`cache/downloads/index.sqlite`) não pôde ser usado. */
"CACHE_UNAVAILABLE";

/**
 *  Códigos do domínio `jarmeta`. O código é contrato: renomear é mudança de contrato;
 *  acrescentar é permitido (só acréscimo, ROADMAP §1).
 */
export type JarmetaErrorCode = 
/**  Bug: invariante quebrada sem código específico. */
"INTERNAL" | 
/**  O arquivo não é um zip/jar válido (corrompido, truncado ou de outro formato). */
"INVALID_ARCHIVE" | 
/**  O jar passa de um limite de segurança (tamanho, número de entradas). */
"LIMIT_EXCEEDED";

/**  Resultado completo de `java_choice`: o Java que o teste vai usar e por quê. */
export type JavaChoice = {
	/**  Major do Java que o teste vai usar. */
	major: number,
	/**  Teto de atualização, quando houver. */
	maxUpdate: number | null,
	/**  Motivo (`USER_CHOICE` quando o usuário escolheu e o Java existe). */
	reason: JavaChoiceReason,
	/**  O Java instalado que será usado; `None` = será baixado ao preparar o teste. */
	runtime: InstalledRuntime | null,
	/**  A decisão automática (sempre presente, para mostrar o motivo mesmo com escolha manual). */
	automatic: JavaDecision,
	/**  O usuário escolheu um Java que não está mais instalado; vale o automático. */
	userChoiceUnavailable: boolean,
};

/**  Por que a política escolheu aquele Java. Código estável, traduzido pela interface. */
export type JavaChoiceReason = 
/**  O usuário escolheu este Java em Ajustes do teste. */
"USER_CHOICE" | 
/**  Forge até o 1.12.2: só abre no Java 8. */
"FORGE_LEGACY_JAVA8" | 
/**  Forge 1.16.5 anterior ao 36.2.26: Java 8 até a atualização 312. */
"FORGE_1165_OLD" | 
/**  O mais novo provado para a faixa, que não é o mais novo que o Warden baixa. */
"NEWEST_PROVEN_FOR_RANGE" | 
/**  O mais novo que o Warden baixa (sem explicação extra). */
"NEWEST_AVAILABLE" | 
/**  Versão sem faixa na tabela: o Java pedido pelo JSON da versão. */
"FROM_VERSION_JSON";

/**  Pedido de escolha do Java para um pack. */
export type JavaChoiceRequest = {
	/**  Versão do Minecraft do `pack.toml`. */
	minecraft: string,
	/**  Loader do pack. */
	loader: LoaderKind,
	/**  Versão exata do loader, quando houver. */
	loaderVersion: string | null,
	/**  O que o JSON da versão diz sobre o Java. */
	versionJson: VersionJavaRequirement,
	/**  Java escolhido pelo usuário em Ajustes do teste (`None` = Automático). */
	userChoice: RuntimeId | null,
};

/**  Decisão da política, antes de olhar os Javas instalados. */
export type JavaDecision = {
	/**  O Java automático (o que a política escolhe sem a escolha do usuário). */
	requirement: JavaRequirement,
	/**  Motivo do Java automático. */
	reason: JavaChoiceReason,
	/**  Regra da tabela que decidiu, quando houver. */
	ruleId: string | null,
	/**  A faixa em texto curto ("1.17 a 1.20.4"), quando a decisão veio da tabela. */
	rangeLabel: string | null,
	/**  O motivo em português (texto da tabela), para "Detalhes técnicos". */
	explanation: string,
	/**  O major mais novo que o Warden baixa ("Por que não o Java N?"). */
	newestMajor: number,
	/**  O major pedido pelo JSON da versão, quando a decisão veio dele. */
	versionJsonMajor: number | null,
};

/**
 *  Códigos do domínio `java`. O código é contrato: renomear é mudança de contrato;
 *  acrescentar é permitido (só acréscimo, ROADMAP §1).
 */
export type JavaErrorCode = 
/**  Bug: invariante quebrada sem código específico. */
"INTERNAL" | 
/**  Este sistema ou processador não tem Java de 64 bits que o Warden saiba baixar. */
"UNSUPPORTED_PLATFORM" | 
/**  A fonte não publica o Java pedido para este sistema. */
"NO_BUILD_AVAILABLE" | 
/**  A fonte (Adoptium ou Mojang) está fora do ar, limitou os pedidos ou recusou o pedido. */
"SOURCE_UNAVAILABLE" | 
/**  A fonte respondeu algo que o Warden não entende. */
"INVALID_RESPONSE" | 
/**  O arquivo baixado não confere com o hash ou o tamanho informados pela fonte. */
"DOWNLOAD_CORRUPTED" | 
/**  O pacote do Java está corrompido, tem caminhos perigosos ou não tem o programa `java`. */
"ARCHIVE_INVALID" | 
/**  O Java não abriu ou não respondeu como um Java. */
"VALIDATION_FAILED" | 
/**  O Java é de 32 bits. */
"NOT_64_BIT" | 
/**  O Java instalado não é a versão pedida. */
"UNEXPECTED_VERSION" | 
/**  O Java pedido não está instalado. */
"RUNTIME_NOT_FOUND" | 
/**  O Java está sendo usado por um jogo aberto. */
"RUNTIME_IN_USE" | 
/**  A pasta do Java não pôde ser movida para o lugar (outro programa a segurou). */
"INSTALL_BLOCKED" | 
/**  Não há regra para esta versão do Minecraft e o JSON da versão não foi lido. */
"VERSION_REQUIREMENT_UNKNOWN" | 
/**  A tabela de compatibilidade embutida é inválida (bug). */
"COMPATIBILITY_TABLE_INVALID";

/**  A tabela de Java de Configurações (CA-T21-04). */
export type JavaOverview = {
	/**  Cada Java instalado. */
	runtimes: RuntimeRow[],
	/**  Packs cujo Java ainda não está instalado (será baixado no próximo teste). */
	packsToDownload: PackJavaUse[],
	/**  Packs sem decisão possível. */
	unresolved: PackJavaUnresolved[],
	/**  Pastas quebradas em `shared/runtimes/` (apagadas por "Remover Javas sem uso"). */
	brokenCount: number,
};

/**  O Java que o pack precisa: o major e, às vezes, um teto de atualização. */
export type JavaRequirement = {
	/**  Major. */
	major: number,
	/**  Atualização máxima (o `312` de "8 ≤ u312"). */
	maxUpdate: number | null,
};

/**  Versão de um Java. */
export type JavaVersion = {
	/**  Versão principal (8, 17, 21, 25…). */
	major: number,
	/**  Segundo número (quase sempre 0). */
	minor: number,
	/**  Atualização de segurança: o `312` de `8u312`, o `12` de `21.0.12`. */
	security: number,
	/**  Quarto número, usado em correções extras (`21.0.12.1`). */
	patch: number,
	/**  Número do build (`+1`, `-b07`); 0 quando não informado. */
	build: number,
};

/**
 *  Códigos do domínio `launcher`. O código é contrato: renomear é mudança de contrato;
 *  acrescentar é permitido (só acréscimo, ROADMAP §1).
 */
export type LauncherErrorCode = 
/**  Bug: invariante quebrada sem código específico. */
"INTERNAL" | 
/**  O nome do jogador não segue `^[A-Za-z0-9_]{3,16}$`. */
"INVALID_PLAYER_NAME" | 
/**  O pack não diz a versão exata do loader (vazia, "stable", "latest"…). */
"LOADER_VERSION_MISSING" | 
/**  A versão do Minecraft não existe (nem na Mojang, nem no loader). */
"MINECRAFT_VERSION_NOT_FOUND" | 
/**  A versão do loader não existe para essa versão do Minecraft. */
"LOADER_VERSION_NOT_FOUND" | 
/**  A instalação do loader (instalador do Forge/NeoForge) falhou. */
"LOADER_INSTALL_FAILED" | 
/**  Um ou mais arquivos do jogo não puderam ser baixados ou vieram corrompidos. */
"DOWNLOAD_FAILED" | 
/**  Os arquivos do jogo instalados estão inconsistentes (JSON da versão, bibliotecas). */
"GAME_FILES_INVALID" | 
/**  O Java não pôde ser usado para instalar ou abrir o jogo. */
"JAVA_UNUSABLE" | 
/**  O modo de entrada direta não existe nesta versão do jogo. */
"QUICK_PLAY_UNSUPPORTED" | 
/**  A linha de comando passa do limite do Windows e o Java não aceita arquivo de argumentos. */
"COMMAND_TOO_LONG" | 
/**  O processo do jogo não pôde ser iniciado. */
"LAUNCH_FAILED" | 
/**  O Warden não conseguiu controlar o processo do jogo (Job Object, grupo de processos). */
"PROCESS_CONTROL_FAILED";

/**  Loaders do catálogo (ADR-0005). O texto é o mesmo do `[versions]` do `pack.toml`. */
export type Loader = 
/**  Forge (todas as versões, inclusive 1.7.10 e 1.12.2). */
"forge" | 
/**  NeoForge (1.20.1 em diante). */
"neoforge" | 
/**  Fabric (1.14 em diante). */
"fabric";

/**  Loader do pack, como a política do Java o vê. */
export type LoaderKind = 
/**  Sem loader. */
"vanilla" | 
/**  Fabric. */
"fabric" | 
/**  Forge. */
"forge" | 
/**  `NeoForge`. */
"neoforge" | 
/**  Quilt. */
"quilt" | 
/**  `LiteLoader`. */
"liteloader";

/**  Uma versão de loader. */
export type LoaderVersion = {
	/**
	 *  A versão como vai no `[versions]` do `pack.toml` (`10.13.4.1614`, `47.1.106`,
	 *  `21.1.252`, `0.19.5`).
	 */
	version: string,
	/**
	 *  Coordenada Maven completa do artefato, que o launcher e o servidor usam para baixar o
	 *  instalador (`net.minecraftforge:forge:1.7.10-10.13.4.1614-1.7.10`,
	 *  `net.neoforged:forge:1.20.1-47.1.106`, `net.fabricmc:fabric-loader:0.19.5`).
	 */
	maven: string,
	/**  Estável: o Fabric diz na meta; no NeoForge, sem `-beta`; no Forge, todas. */
	stable: boolean,
	/**  A "recomendada" do `promotions_slim.json` (só Forge). */
	recommended: boolean,
};

/**
 *  As versões de um loader para uma versão do Minecraft. Lista vazia: o loader não existe
 *  para essa versão (CA-T03-03).
 */
export type LoaderVersions = {
	/**  O loader. */
	loader: Loader,
	/**  A versão do Minecraft pedida. */
	minecraft: string,
	/**  Da mais nova para a mais antiga, sem as versões da lista de quebradas. */
	versions: LoaderVersion[],
	/**
	 *  A versão pré-selecionada no assistente (SPEC T03): Forge, a recomendada ou, sem ela, a
	 *  mais recente; NeoForge e Fabric, a mais recente estável ou, sem estável, a mais
	 *  recente.
	 */
	preselected: string | null,
	/**  De quando é a lista. */
	freshness: Freshness,
};

/**  Nível de detalhe dos registros (Configurações → Privacidade e registros). */
export type LogLevel = 
/**  `info` para tudo. */
"normal" | 
/**  `debug` para o código do Warden. */
"detailed";

/**
 *  Onde está o botão maximizar, em pixels CSS, medido pela interface. A posição horizontal é a
 *  distância até a borda direita da janela, que não muda quando a janela muda de largura.
 */
export type MaximizeButtonArea = {
	/**  Distância da borda direita do botão até a borda direita da janela. */
	right: number | null,
	/**  Distância do topo do botão até o topo da janela. */
	top: number | null,
	/**  Largura do botão. */
	width: number | null,
	/**  Altura do botão. */
	height: number | null,
};

/**  Uma versão do Minecraft. */
export type MinecraftVersion = {
	/**  O id da Mojang (`1.20.1`, `26.3`, `26.4-snapshot-2`). */
	id: string,
	/**  Tipo. */
	kind: MinecraftVersionKind,
	/**  Data de lançamento, como a Mojang escreve (RFC 3339). */
	releaseTime: string,
	/**
	 *  Anterior a 1.7.10 pela ordem do manifesto: aparece com a etiqueta "melhor esforço"
	 *  (ADR-0005).
	 */
	bestEffort: boolean,
};

/**  Tipo de uma versão no manifesto da Mojang. */
export type MinecraftVersionKind = 
/**  Versão final. */
"release" | 
/**  Snapshot, pre-release ou release candidate (fora da v1, ADR-0005). */
"snapshot" | 
/**  Beta antiga (2010–2011). */
"old_beta" | 
/**  Alfa antiga (2010). */
"old_alpha" | 
/**  Tipo que o Warden ainda não conhece. */
"other";

/**
 *  As versões do Minecraft, na ordem oficial do manifesto da Mojang (da mais nova para a mais
 *  antiga). Nunca reordene por texto ou semver: existem `26.3` e `1.21.11`.
 */
export type MinecraftVersions = {
	/**  Todas as versões, na ordem do manifesto. */
	versions: MinecraftVersion[],
	/**  `latest.release` do manifesto. */
	latestRelease: string | null,
	/**  `latest.snapshot` do manifesto. */
	latestSnapshot: string | null,
	/**  De quando é a lista. */
	freshness: Freshness,
};

/**
 *  Códigos do domínio `mixin`. O código é contrato: renomear é mudança de contrato;
 *  acrescentar é permitido (só acréscimo, ROADMAP §1).
 */
export type MixinErrorCode = 
/**  Bug: invariante quebrada sem código específico. */
"INTERNAL";

/**
 *  Códigos do domínio `modrinth`. O código é contrato: renomear é mudança de contrato;
 *  acrescentar é permitido (só acréscimo, ROADMAP §1).
 */
export type ModrinthErrorCode = 
/**  Bug: invariante quebrada sem código específico. */
"INTERNAL" | 
/**  O projeto não existe (ou não é público). */
"PROJECT_NOT_FOUND" | 
/**  A versão não existe. */
"VERSION_NOT_FOUND" | 
/**  O Modrinth não encontrou o endereço pedido. */
"NOT_FOUND" | 
/**  O Modrinth limitou as requisições (429) por mais tempo do que o Warden espera sozinho. */
"RATE_LIMITED" | 
/**  O Modrinth está fora do ar ou com erro (5xx). */
"UNAVAILABLE" | 
/**  O Modrinth recusou o pedido (4xx). */
"REQUEST_REJECTED" | 
/**  O Modrinth respondeu algo que o Warden não entende. */
"INVALID_RESPONSE" | 
/**  O cache local do Modrinth (`metadata.sqlite`) não pôde ser lido ou gravado. */
"CACHE_UNAVAILABLE";

/**  Identificador de uma operação longa no registro de operações (ARCHITECTURE §15). */
export type OperationId = string;

/**
 *  Tipo da operação, como chave estável (`"pack.create"`, `"test.start"`…). A interface usa
 *  para escolher o texto; cada tarefa define as suas constantes no próprio módulo.
 */
export type OperationKind = string;

/**  O que a interface sabe de uma operação. */
export type OperationSnapshot = {
	/**  Identificador. */
	id: OperationId,
	/**  Tipo. */
	kind: OperationKind,
	/**  Pack em que atua, se for o caso. */
	packId: PackId | null,
	/**  Situação. */
	state: OperationState,
	/**  Etapa atual. */
	stage: OperationStage | null,
	/**  Progresso da etapa atual. */
	progress: Progress | null,
	/**  Se "Cancelar" está disponível agora. */
	cancellable: boolean,
	/**  Início (milissegundos desde 1970, UTC). */
	startedAtMs: number,
	/**  Fim, quando terminou. */
	finishedAtMs: number | null,
	/**  Erro, quando terminou com erro. */
	error: AppError | null,
};

/**  Etapa atual. */
export type OperationStage = {
	/**  Identificador estável da etapa. */
	id: string,
	/**  Chave do texto no catálogo. */
	labelKey: string,
};

/**  Situação de uma operação. */
export type OperationState = 
/**  Em andamento. */
"running" | 
/**  Esperando outra operação no mesmo pack ("Aguardando outra operação neste pack"). */
"waitingForLock" | 
/**  Cancelamento pedido; ainda parando. */
"cancelling" | 
/**  Terminou bem. */
"succeeded" | 
/**  Terminou com erro. */
"failed" | 
/**  Cancelada. */
"cancelled";

/**
 *  `operation-updated`: uma operação mudou de estado, etapa ou progresso (painel Tarefas,
 *  T22).
 */
export type OperationUpdated = OperationSnapshot;

/**  Parte do pack que mudou, para a interface invalidar só o necessário. */
export type PackArea = 
/**  Mods, resource packs, shaders (lista do pack). */
"inventory" | 
/**  Configs. */
"configs" | 
/**  Informações do pack. */
"meta" | 
/**  Histórico de versões. */
"history";

/**  `pack-changed`: o pack mudou (escrita do Warden ou mudança externa). */
export type PackChanged = {
	/**  Pack alterado. */
	packId: PackId,
	/**  Partes alteradas. */
	areas: PackArea[],
};

/**
 *  Identificador de um pack: gerado na criação ou importação e gravado em
 *  `.warden/project.toml`. Todo comando que atua num pack o recebe como primeiro argumento
 *  (ARCHITECTURE §4.1).
 */
export type PackId = string;

/**  Um pack cujo Java não pôde ser decidido (versão sem regra e sem o JSON da versão). */
export type PackJavaUnresolved = {
	/**  Identificador do pack. */
	packId: PackId,
	/**  Nome do pack. */
	name: string,
	/**  Versão do Minecraft. */
	minecraft: string,
};

/**  Um pack na tabela de Java, com o Java que ele usa e por quê. */
export type PackJavaUse = {
	/**  Identificador do pack. */
	packId: PackId,
	/**  Nome do pack. */
	name: string,
	/**  Versão do Minecraft do pack. */
	minecraft: string,
	/**  A escolha (major, motivo e o Java instalado, se houver). */
	choice: JavaChoice,
};

/**  Linha pronta para a lista, sem executar diagnóstico. */
export type PackRow = {
	/**  Identificador. */
	id: PackId,
	/**  Pasta. */
	path: string,
	/**  Nome legível, quando o manifesto puder ser lido. */
	name: string,
	/**  Versão do Minecraft. */
	minecraft: string | null,
	/**  Loader. */
	loader: string | null,
	/**  Versão do loader. */
	loaderVersion: string | null,
	/**  Versão do pack. */
	version: string | null,
	/**  Última alteração conhecida dos arquivos do pack, em milissegundos Unix. */
	modifiedAtMs: number | null,
	/**  Estado da pasta. */
	status: PackStatus,
	/**  Detalhe técnico se o manifesto for inválido. */
	detail: string | null,
	/**  Motivo pelo qual o repositório só pode ser aberto para leitura. */
	readOnlyReason: string | null,
	/**  Quantidade de arquivos alterados desde a última versão salva. */
	unsavedFiles: number,
	/**  Último teste. */
	lastTest: string | null,
};

/**  Situação de uma linha de Meus packs. */
export type PackStatus = 
/**  Pack legível e pasta presente. */
"ready" | 
/**  Pasta registrada não existe mais. */
"folderMissing" | 
/**  Manifesto não pôde ser lido. */
"invalidPack";

/**
 *  Códigos do domínio `packwizCli`. O código é contrato: renomear é mudança de contrato;
 *  acrescentar é permitido (só acréscimo, ROADMAP §1).
 */
export type PackwizCliErrorCode = 
/**  Bug: invariante quebrada sem código específico. */
"INTERNAL" | 
/**  O executável do packwiz não foi encontrado. */
"BINARY_NOT_FOUND" | 
/**  O sistema não deixou iniciar o packwiz. */
"SPAWN_FAILED" | 
/**  A pasta não tem `pack.toml`. */
"PACK_FILE_MISSING" | 
/**  O packwiz terminou com erro (código de saída diferente de zero). */
"COMMAND_FAILED" | 
/**  O packwiz disse que deu certo, mas os arquivos relidos não conferem. */
"POSTCONDITION_FAILED" | 
/**
 *  O comando precisava da chave da CurseForge e ela não foi informada (mesmo texto do
 *  código da `warden-curseforge`, sem o `_` que o `CurseForge` geraria).
 */
"CURSEFORGE_KEY_MISSING" | 
/**  Há mods da CurseForge que só podem ser baixados à mão. */
"MANUAL_DOWNLOADS_REQUIRED" | 
/**  Um arquivo não pôde ser baixado e a exportação ficaria incompleta. */
"DOWNLOAD_FAILED" | 
/**  A pasta do pack tem um link simbólico ou junção, que o Warden não segue. */
"LINK_IN_PACK";

/**
 *  Códigos do domínio `packwiz`. O código é contrato: renomear é mudança de contrato;
 *  acrescentar é permitido (só acréscimo, ROADMAP §1).
 */
export type PackwizErrorCode = 
/**  Bug: invariante quebrada sem código específico. */
"INTERNAL" | 
/**  O arquivo não é um TOML válido. */
"INVALID_TOML" | 
/**  Um campo existe, mas com o tipo errado (texto onde se esperava número etc.). */
"INVALID_FIELD_TYPE" | 
/**  Um campo tem um valor que o packwiz não aceita (`pack-format` desconhecido etc.). */
"INVALID_FIELD_VALUE" | 
/**  Um caminho do índice ou de um metafile tenta sair da pasta do pack. */
"UNSAFE_PATH" | 
/**  Um link não pôde ser interpretado. */
"INVALID_URL" | 
/**  Formato de hash que o packwiz não conhece. */
"UNKNOWN_HASH_FORMAT";

/**
 *  Códigos do domínio `perf`. O código é contrato: renomear é mudança de contrato;
 *  acrescentar é permitido (só acréscimo, ROADMAP §1).
 */
export type PerfErrorCode = 
/**  Bug: invariante quebrada sem código específico. */
"INTERNAL";

/**  Sistema em que o app roda. */
export type Platform = 
/**  Windows (WebView2). */
"windows" | 
/**  Linux (WebKitGTK; só na CI). */
"linux" | 
/**  Outro (não suportado). */
"other";

/**  Avisos anteriores à exportação. */
export type Preflight = {
	/**  Arquivos suspeitos encontrados na pasta, inclusive fora do índice. */
	hygiene: HygieneFinding[],
	/**  O estado atual diverge da última versão salva. */
	unsavedChanges: boolean,
	/**  A contagem de erros de diagnóstico fica ausente até a API de D-01 existir. */
	diagnosticErrors: number | null,
};

/**  Um arquivo distribuído, em ordem de caminho. */
export type PreviewFile = {
	/**  Caminho relativo, com `/`. */
	path: string,
	/**  Bytes reais da origem. */
	bytes: number,
	/**  Referência `.pw.toml`, sem o jar do mod. */
	reference: boolean,
	/**  Arquivo distribuído em bytes, sem ser referência nem controle. */
	local: boolean,
	/**  Arquivo de `config/` ou `defaultconfigs/`. */
	config: boolean,
	/**  Alertas deste arquivo. */
	alerts: ExportAlert[],
};

/**  Contagem e tamanho por pasta, incluindo a raiz (`.`). */
export type PreviewFolder = {
	/**  Caminho relativo da pasta. */
	path: string,
	/**  Arquivos nesta pasta e nas subpastas. */
	files: number,
	/**  Soma dos tamanhos nesta pasta e nas subpastas. */
	bytes: number,
};

/**  Quanto já foi feito. */
export type Progress = {
	/**  Quantidade feita. */
	current: number,
	/**  Total, quando conhecido. */
	total: number | null,
	/**  Unidade de `current` e `total`. */
	unit: ProgressUnit,
};

/**  Unidade do progresso, para a interface formatar o número. */
export type ProgressUnit = 
/**  Itens (mods, arquivos, etapas). */
"items" | 
/**  Bytes (downloads, cópias). */
"bytes";

/**  Códigos do domínio `project`; somente acréscimos são compatíveis. */
export type ProjectErrorCode = 
/**  Invariante interna quebrada. */
"INTERNAL" | 
/**  Nome ou campo inválido. */
"INVALID_INPUT" | 
/**  Destino já contém arquivos. */
"DESTINATION_NOT_EMPTY" | 
/**  Pack não registrado. */
"PACK_NOT_FOUND" | 
/**  Pasta de um pack registrado desapareceu. */
"FOLDER_MISSING" | 
/**  Manifesto não é um packwiz válido. */
"INVALID_PACK" | 
/**  Loader não suportado ou múltiplo. */
"UNSUPPORTED_LOADER" | 
/**  A versão escolhida não pertence ao catálogo do loader. */
"INVALID_LOADER_VERSION" | 
/**  Pasta ou identificador já registrado. */
"ALREADY_REGISTERED" | 
/**  Arquivo mudou entre planejamento e escrita. */
"PACK_CHANGED_EXTERNALLY" | 
/**  Repositório está em estado somente leitura. */
"READ_ONLY" | 
/**  A confirmação para apagar não corresponde ao nome do pack. */
"TRASH_CONFIRMATION";

/**
 *  Identificador de um Java instalado: `<fonte>-<major>-<versão>-<processador>`, que também é
 *  o nome da pasta (`temurin-21-21.0.12.1+1-x64`, `temurin-8-8u312-b07-x64`).
 * 
 *  Ao ler (inclusive pelo IPC), o texto passa por [`RuntimeId::parse`]: um id nunca vira um
 *  caminho fora de `shared/runtimes/`.
 */
export type RuntimeId = string;

/**  Uma linha da tabela de Java de Configurações. */
export type RuntimeRow = {
	/**  O Java. */
	runtime: InstalledRuntime,
	/**  Os packs que o usam, com o motivo. */
	packs: PackJavaUse[],
	/**  Se um jogo aberto está usando este Java. */
	inGame: boolean,
};

/**  De onde veio o Java. */
export type RuntimeSource = 
/**  Eclipse Temurin, pelo Adoptium (fonte padrão). */
"temurin" | 
/**  Runtime oficial da Mojang (alternativa). */
"mojang";

/**  Uma atualização instalada. */
export type RuntimeUpdate = {
	/**  O Java antigo. */
	from: RuntimeId,
	/**  O Java novo. */
	to: InstalledRuntime,
	/**  Se o antigo já foi removido (não estava em uso). */
	oldRemoved: boolean,
};

/**
 *  Códigos do domínio `scripts`. O código é contrato: renomear é mudança de contrato;
 *  acrescentar é permitido (só acréscimo, ROADMAP §1).
 */
export type ScriptsErrorCode = 
/**  Bug: invariante quebrada sem código específico. */
"INTERNAL";

/**  Um segredo que o Warden guarda. Não existe "ler segredo" pela interface. */
export type SecretKind = 
/**  Chave da API da CurseForge. */
"curseforge" | 
/**  Chave da API do Gemini. */
"gemini" | 
/**  Token do GitHub (publicar versão). */
"github";

/**  Resultado de "Testar". */
export type SecretTestResult = 
/**  A API aceitou a chave. */
{ status: "valid" } | 
/**  Ainda não há como testar esta chave nesta versão. */
{ status: "notTestable" };

/**  Códigos do domínio `secrets` (ARCHITECTURE §5). Só acréscimo. */
export type SecretsErrorCode = 
/**  Bug. */
"INTERNAL" | 
/**
 *  O valor digitado não serve como chave (vazio, com quebra de linha, aspas simples ou
 *  longo demais).
 */
"INVALID_VALUE" | 
/**  A chave pedida não está configurada. */
"NOT_CONFIGURED" | 
/**  O cofre do sistema não está acessível (bloqueado, serviço parado, sem permissão). */
"VAULT_UNAVAILABLE" | 
/**  O cofre do sistema recusou a operação. */
"VAULT_FAILED" | 
/**  O arquivo `.env` existe mas não pôde ser lido como texto. */
"ENV_FILE_UNREADABLE" | 
/**  Depois de gravar, a releitura não trouxe o mesmo valor. */
"VERIFY_FAILED" | 
/**  A troca de modo falhou; as chaves continuam no modo anterior. */
"BACKEND_SWITCH_FAILED";

/**  O que a interface sabe das chaves: onde ficam e quais estão configuradas. */
export type SecretsStatus = {
	/**  Armazenamento em uso. */
	backend: BackendKind,
	/**  Chave da CurseForge configurada. */
	curseforge: boolean,
	/**  Chave do Gemini configurada. */
	gemini: boolean,
	/**  Token do GitHub configurado. */
	github: boolean,
};

/**
 *  Códigos do domínio `server`. O código é contrato: renomear é mudança de contrato;
 *  acrescentar é permitido (só acréscimo, ROADMAP §1).
 */
export type ServerErrorCode = 
/**  Bug: invariante quebrada sem código específico. */
"INTERNAL";

/**  Configurações do app. */
export type Settings = {
	/**  Versão do formato. */
	schemaVersion?: number,
	/**  Onde ficam as chaves (muda só por `secrets_backend_set`). */
	secretsBackend?: BackendKind,
	/**
	 *  Pasta padrão dos packs; `null` = a pasta padrão do sistema (Documentos\Warden).
	 *  Muda por um comando que abre o diálogo nativo (ARCHITECTURE §4.1), não por
	 *  `settings_update`.
	 */
	packsDir?: string | null,
	/**  Nome do jogador no perfil offline do teste. */
	playerName?: string,
	/**  Nível de detalhe dos registros. */
	logLevel?: LogLevel,
	/**  Mostrar diferenças antes de salvar uma config. */
	configDiffBeforeSave?: boolean,
	/**  Mostrar versões beta e alfa dos mods. */
	showPrereleaseVersions?: boolean,
	/**  Intervalo da verificação automática de atualizações, em horas (0 = desligada). */
	updateCheckIntervalHours?: number,
	/**  Memória padrão do teste. */
	testMemory?: TestMemory,
	/**  Quando a EULA do Minecraft foi aceita (RFC 3339), para o servidor local (P1, T27). */
	eulaAcceptedAt?: string | null,
};

/**  Mudanças pedidas pela interface (`settings_update`). Campo ausente = não muda. */
export type SettingsPatch = {
	/**
	 *  Nome do jogador: 3 a 16 caracteres, letras sem acento, números e `_` (regra do
	 *  Minecraft).
	 */
	playerName?: string | null,
	/**  Nível dos registros. */
	logLevel?: LogLevel | null,
	/**  Diferenças antes de salvar. */
	configDiffBeforeSave?: boolean | null,
	/**  Versões beta e alfa. */
	showPrereleaseVersions?: boolean | null,
	/**  Intervalo da verificação de atualizações (0 a 720 horas). */
	updateCheckIntervalHours?: number | null,
	/**  Memória do teste (512 a 65536 MB quando fixa). */
	testMemory?: TestMemory | null,
};

/**  O que a interface precisa saber das configurações além do `settings.json` (T01, T21). */
export type SettingsStatus = {
	/**  O `settings.json` ainda não existe: o app abre na primeira execução (T01). */
	firstRun: boolean,
	/**  Pasta onde os packs novos são criados (a escolhida ou a padrão do sistema). */
	packsDir: string,
	/**  Pasta padrão do sistema (Documentos\Warden). */
	defaultPacksDir: string,
};

/**  Memória padrão do teste (Configurações → Teste). */
export type TestMemory = 
/**  O Warden escolhe pela quantidade de mods e pela memória do computador. */
{ mode: "auto" } | 
/**  Valor fixo, em MB. */
{ mode: "fixed"; 
/**  Memória máxima do Java, em MB. */
mb: number };

/**
 *  `title-bar-maximize`: o mouse entrou, saiu ou apertou o botão maximizar da barra de título
 *  própria (UI-01). Sobre esse botão quem recebe o mouse é uma janela nativa transparente
 *  (`window_chrome`), para o Windows 11 mostrar o menu de encaixe; o evento devolve à interface
 *  o estado que ela desenha.
 */
export type TitleBarMaximize = {
	/**  Mouse sobre o botão. */
	hovered: boolean,
	/**  Botão do mouse apertado sobre o botão. */
	pressed: boolean,
};

/**  Resultado de "Procurar atualizações do Java". */
export type UpdateReport = {
	/**  Atualizações instaladas. */
	updated: RuntimeUpdate[],
	/**  Javas que já estavam na versão mais nova. */
	upToDate: RuntimeId[],
	/**  Javas que não puderam ser conferidos agora (fonte fora do ar). */
	failed: RuntimeId[],
	/**  Javas substituídos antes e removidos agora. */
	removed: RuntimeId[],
};

/**  O que o JSON da versão do Minecraft diz sobre o Java (`javaVersion`). */
export type VersionJavaRequirement = 
/**  O JSON da versão não foi lido (a tabela costuma bastar). */
{ kind: "notLoaded" } | 
/**  O JSON não tem `javaVersion` (versões antigas): Java 8. */
{ kind: "absent" } | 
/**  `javaVersion.majorVersion`. */
{ kind: "major"; 
/**  O major pedido. */
major: number };

/**
 *  Códigos do domínio `versioning`. O código é contrato: renomear é mudança de contrato;
 *  acrescentar é permitido (só acréscimo, ROADMAP §1).
 */
export type VersioningErrorCode = 
/**  Bug: invariante quebrada sem código específico. */
"INTERNAL" | 
/**  A pasta do pack ainda não tem histórico de versões. */
"NOT_VERSIONED" | 
/**  A pasta do pack já tem histórico de versões. */
"ALREADY_VERSIONED" | 
/**  O histórico pertence a outro usuário do Windows (proteção da libgit2). */
"REPO_NOT_OWNED" | 
/**  Outro programa está mexendo no histórico agora (arquivo de trava do git). */
"REPO_LOCKED" | 
/**  O histórico está no meio de uma operação feita por fora (merge, rebase…). */
"REPO_BUSY" | 
/**  O histórico não está numa linha de versões (HEAD destacado). */
"DETACHED_HEAD" | 
/**  O histórico tem conflitos não resolvidos. */
"CONFLICTS" | 
/**  O texto não é uma versão no formato X.Y.Z. */
"INVALID_VERSION" | 
/**  A versão pedida não é maior que a última salva. */
"VERSION_NOT_GREATER" | 
/**  Já existe uma versão salva com esse número. */
"VERSION_EXISTS" | 
/**  Nada mudou desde a última versão salva. */
"NOTHING_CHANGED" | 
/**  A versão pedida não existe no histórico. */
"VERSION_NOT_FOUND" | 
/**  O ponto de segurança pedido não existe. */
"SAFETY_POINT_NOT_FOUND" | 
/**  A versão já foi publicada e não pode deixar de ser versão final. */
"VERSION_PUBLISHED" | 
/**  Um arquivo do pack está aberto em outro programa (o jogo, o antivírus…). */
"FILE_IN_USE" | 
/**  A restauração falhou e o pack não pôde voltar sozinho ao estado anterior. */
"ROLLBACK_FAILED" | 
/**  Falha da biblioteca git ao ler ou gravar o histórico. */
"GIT_FAILED";

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

