[package]
name = "warden-launcher"
description = "Interface LauncherEngine, perfil offline, supervisão do processo do jogo e leitura de logs."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
warden-core.workspace = true
warden-java.workspace = true
warden-catalog.workspace = true
serde.workspace = true
specta = { workspace = true, features = ["derive"] }

[lints]
workspace = true
